### 전체 조회
GET http://localhost:8080/developers

### 단건 조회
GET http://localhost:8080/developers/newbie

### 단건 생성 1
POST http://localhost:8080/create-developer
Content-Type: application/json

{
  "developerLevel": "NEW",
  "developerSkillType": "BACK_END",
  "experienceYears": 2,
  "memberId": "newbie",
  "name": "okjaeook",
  "age": 26
}

### 단건 생성 2
POST http://localhost:8080/create-developer
Content-Type: application/json

{
  "developerLevel": "SENIOR",
  "developerSkillType": "FRONT_END",
  "experienceYears": 10,
  "memberId": "senior",
  "name": "heo",
  "age": 40
}

### 단건 수정
PATCH http://localhost:8080/developer/newbie
Content-Type: application/json

{
  "developerLevel": "JUNGNIOR",
  "developerSkillType": "FRONT_END",
  "experienceYears": 5,
  "memberId": "newbie"
}

### 단건 삭제
DELETE http://localhost:8080/developer/delete/newbie
